config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  root to: 'flats#index'
  resources :flats
  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/flat.rb
class Flat < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/flats_controller.rb
class FlatsController < ApplicationController
  before_action :set_flat, only: [:show, :destroy, :edit, :update]
  
  def index
    @flats = Flat.all
  end

  def new
    @flat = Flat.new
  end

  def create
    @flat = Flat.new(flat_params)
      if @flat.save
        redirect_to @flat, notice: "Flat added!"
      else
        render :new, status: :unprocessable_entity
      end
  end

  def show

  end

  def edit

  end

  def update

    if @flat.update(flat_params)
      redirect_to @flat, notice: "Flat updated!"
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @flat.destroy
    redirect_to flats_path, notice: "Flat was deleted"
  end

  private

  def flat_params
    params.require(:flat).permit(:name, :address, :description, :price_per_night, :number_of_guests)
  end

  def set_flat
    @flat = Flat.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/flats_helper.rb
module FlatsHelper
end

app/views/flats/_form.html.erb
  <%=f.input :name%>
  <%=f.input :address%>
  <%=f.input :description%>
  <%=f.input :price_per_night%>
  <%=f.input :number_of_guests%>

app/views/flats/edit.html.erb
<div class="container">
  <h1>Edit flat</h1>
  <%=simple_form_for(@flat) do |f| %>
    <%= render "form", f: f %>
    <%= f.submit%>
  <%end%>
</div>

app/views/flats/index.html.erb
<div class="container">
  <h1>Places to stay</h1>
  <ul>
    <div class="row">
      <% @flats.each do |flat| %>
        <div class="card col-4 m-1">
          <h2><%= flat.name %></h2>
          <p><strong>address:</strong> <%= flat.address %></p>
          <i class="fa-solid fa-sterling-sign"><%=flat.price_per_night %></i>
          <i class="fa-solid fa-user-group"><%=flat.number_of_guests%></i>
          <%= link_to "more info", flat %>
        </div>
      <% end %>
    </div>
  </ul>
  <%=link_to "Add", new_flat_path%>

</div>

app/views/flats/new.html.erb
<div class="container">
  <h1>Add a new flat</h1>
  <%=simple_form_for(@flat) do |f| %>
    <%= render "form", f: f %>
    <%= f.submit%>
  <%end%>
</div>

app/views/flats/show.html.erb
<div class="container">
  <h1><%= @flat.name %></h1>
  <p><%= @flat.description %></p>
  <i class="fa-solid fa-sterling-sign"><%=@flat.price_per_night %></i>
  <i class="fa-solid fa-user-group"><%=@flat.number_of_guests%></i>
  <%=link_to "back", flats_path%>
  <%= link_to "Edit", edit_flat_path(@flat)%>
  <%= link_to flat_path(@flat), data: {turbo_method: :delete, turbo_confirm: "Are you sure?" } do %>
    <i class='fa-regular fa-trash-can'></i>
  <%end%>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsSimpleAirbnb</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v6.1.2/css/all.css">
  </head>

  <body>
    <%= yield %>
  </body>
</html>